### ISSUE TITLE
Übungsblatt KlassenObjektDiagramme Aufgabe 4 [Assignee: Felix Haala] [Reviewer: Robin Grellner, Alexander Heinritzi]

### ISSUE THREAD

**Issue by fhaala** [sweIhm-ws2018-19/skillproject-do-2#1]
Hier diskutieren wir die Lösung zu oben genannter Aufgabe. Anbei der zugehörige Ausschnitt aus der Angabe. Der Code befindet sich unter: https://github.com/sweIhm-ws2018-19/skillproject-do-2/tree/master/UML/konten/src

![bildschirmfoto 2018-10-18 um 14 29 37](https://user-images.githubusercontent.com/43846490/47154363-6bedf980-d2e2-11e8-903a-6e0af6b62140.png)

**Comment by RobinGrellner** [comment]
Reicht beim Konstruktor der Adresse nicht der Standard Konstruktor, da kein überladener Konstruktor im Klassendiagramm angegeben ist?

**Comment by fhaala** [comment]
Der Ctor ist nicht explizit gefordert. Hab ihn einfach dazu gemacht, weil ich das bei den anderen Klassen auch machen musste um sicherzustellen, dass bei Kunde und Konto mindestens 1 Objekt vom jeweils anderen Typ enthalten ist. Außerdem war es bisher Konvention keine Standard-Ctoren zu verwenden, weil Custom-Ctoren vorhersehbarer sind.

**Comment by crownver** [comment]
Gut, das das unsere Konventionen aus Softwareentwicklung waren stimmt aber sind diese hier noch relevant oder wäre es nicht besser genau dem vorgegebenen UML zu folgen?

**Comment by fhaala** [comment]
Wäre bestimmmt nicht verkehrt, geht aber einfach nicht anders umzusetzen. Hatte das allerdings gerade im Fall von Kunden/Konten mit Frau Socher besprochen und die hat grünes Licht gegeben.

**Comment by crownver** [comment]
Alles klar, dann können mir von mir aus schließen, sollte ja geklärt sein.

**Comment by RobinGrellner** [comment]
Aus meiner Sicht sollte das dann auch passen soweit!  :)
