### ISSUE TITLE
Beschreibung der Anwendungsfälle 

### ISSUE THREAD

**Issue by crownver** [sweIhm-ws2018-19/skillproject-do-2#15]
Eine Beschreibung aller Anwendungsfälle ist zu erarbeiten und soll anschließend hier und in der zugehörigen Ordnerstruktur eingefügt werden.

**Comment by crownver** [comment]
Bitte die Dokumente noch einfügen! 
Aus dem derzeitigen Stand in unserer internen Struktur lässt sich der Anwendungsfall "Nächster Drink" als eigenständiger Punkt ablesen, soll das so sein? Eig wird diese Funktion ja an die drei Unterfunktionen des "Drink vorschlagen" gehängt und kann nur dort abgerufen werden.

**Comment by RobinGrellner** [comment]
@crownver  Ich denke dass es als eigenständiger Punkt behandelt werden muss, da ja auch ohne solche Eigenschaften ein zufälliger Drink ausgewählt werden kann. Daher würde ja dieser fall auch benötigt werden, was die Existenz dieser "Funktion" rechtfertigen sollte

**Comment by RobinGrellner** [comment]
Hier die Anwengungsfälle:
![grafik](https://user-images.githubusercontent.com/32230968/48361084-00a90480-e6a1-11e8-9431-24165297742e.png)
![grafik](https://user-images.githubusercontent.com/32230968/48361154-2e8e4900-e6a1-11e8-9bb9-e8f7bf0a3fb2.png)
![grafik](https://user-images.githubusercontent.com/32230968/48361176-3d74fb80-e6a1-11e8-9886-16f99dfd776b.png)
![grafik](https://user-images.githubusercontent.com/32230968/48361192-46fe6380-e6a1-11e8-8c38-e086a94a3e9f.png)
![grafik](https://user-images.githubusercontent.com/32230968/48361200-4ebe0800-e6a1-11e8-9004-1c49b0d43b87.png)
![grafik](https://user-images.githubusercontent.com/32230968/48361263-6f865d80-e6a1-11e8-9d92-cf25e5e4659e.png)
![grafik](https://user-images.githubusercontent.com/32230968/48361274-76ad6b80-e6a1-11e8-8a5f-0617a0aee15c.png)
![grafik](https://user-images.githubusercontent.com/32230968/48361289-8036d380-e6a1-11e8-9a1a-8ea99dd4bbe1.png)
![grafik](https://user-images.githubusercontent.com/32230968/48361313-8d53c280-e6a1-11e8-8df8-a0abd9fffca8.png)
![grafik](https://user-images.githubusercontent.com/32230968/48361337-96dd2a80-e6a1-11e8-99d5-07ecad97f7fa.png)
![grafik](https://user-images.githubusercontent.com/32230968/48361356-a2c8ec80-e6a1-11e8-8143-1d30b7bafa33.png)
![grafik](https://user-images.githubusercontent.com/32230968/48361381-aceaeb00-e6a1-11e8-8a84-5ff76e774b26.png)
![grafik](https://user-images.githubusercontent.com/32230968/48361401-b5432600-e6a1-11e8-98ec-6841eaeb86af.png)

**Comment by crownver** [comment]
@RobinGrellner da wir eig geklärt hatten das ein Drink nicht ohne die Angabe "Alkohol/frei" ausgewählt werden kann, finde ich rechtfertigt sich diese Alleinstellung nicht. 
Diese Funktion muss des Weiteren, finde ich, immer einer anderen nachgestellt worden sein, da ich ja, laut deinem Diagramm, sonst gleich zu Beginn nach dem nächsten Drink fragen könnte, was, wie ich finde, sinnlos wäre.

**Comment by crownver** [comment]
Ich würde daher die anderen Bitten ihre Meinung dazu abzugeben, ich bin stark dafür diesen Punkt aus dem "Hauptmenü" zu entfernen.

**Comment by Rybak07** [comment]
Ich finde, dass beim Anwendungsfall "Drink löschen" noch einmal gefragt werden soll, ob man den Drink wirklich löschen will bevor man ihn löscht. Möglicherweise wurde die Eingabe auch nur falsch verstanden. Wird dann ein Drink gelöscht wäre das sehr ärgerlich.

**Comment by fhaala** [comment]
Das mit dem bestätigen der Löschung habe ich im Prototypen und in meiner User Stories aufgegriffen. 

Den Punkt Drink vorschlagen ohne Zusatz (Alkohol, Geschmack, Zutat) fand bisher keine Berücksichtigung. Soll @RobinGrellner hier nachbessern oder ich?

Meine User Stories und der Prototyp sind aktuell auch so aufgebaut, dass die Frage nach Alkohol ein eigener Menüpunkt ist und nicht kombiniert wird. Hier sollten wir auch entscheiden, wie es weitergehen soll. Ich bin natürlich für meine Variante, genau so wie oben ;-)

**Comment by crownver** [comment]
Das bestätigen der Löschung finde ich auch sehr wichtig. Muss dies hier auch berücksichtigt werden? 

Ich würde es dabei belassen und dem ganzen keine Berücksichtigung schenken. Ich finde den Prototypen, so wie er jetzt ist der Idee sehr nahe und somit auch sehr gut. 

Ich wäre für eine zwingende Abfrage des Alkohols bei jedem Vorschlag. 

**Mir persönlich jedoch am wichtigsten: Der Punkt "Nächster Drink" - wie soll damit umgegangen werden?** 
Ich persönlich würde ihn gerne entfernen aufgrund oben genannter Argumente.

**Comment by RobinGrellner** [comment]
@crownver Das mit dem Drink nachfragen ist durch die Anwendungsfälle abgedeckt. Meines Wissens nach muss das nicht im Anwendungsfalldiagramm auftreten, sondern nur in der UseCase beschreibung. Das mit der Einigung, dass mindestens eine Eigenschaft mit angegeben werden muss hab ich wohl nicht mitbekommen. In meinen Augen ist das auch eher Unsinn, weil man sonst ja immer spezifizieren müsste, und eine einfach abfrage a`la "Gib mir einfach irgendwas" ja nicht möglich wäre.
Aber ich richte mich nach der Masse, daher wäre @Rybak07 's Meinung dazu auch noch wichtig. 
Das mit dem Drink löschen werd ich noch in die Anwendungsfallbeschreibung mit aufnehmen. Es verlangt keinen extra Use Case!

**Comment by RobinGrellner** [comment]
Vielleicht konkretisiere ich nochmal meine Aussagen:
1. Bezüglich der Bestätigung der Löschung bin ich da auf eurer Seite, das Feature macht definitiv Sinn.
2. Dass Drinks ohne Eigenschaft abgefragt werden sollen finde ich nur Sinnvoll, wie schon oben genannt. 
3. Voranstellen eines Drinks vor der frage nach dem nächsten Drink ist bereits implementiert. Dies muss nicht im Diagramm, sondern in den Anwendungsfallbeschreibungen konkretisiert werden.

**Comment by fhaala** [comment]
So wie ich das im Unterricht mitbekommen habe, müssen hier die Intents dargestellt werden. Einfach gesagt, sind das genau die Optionen, die wir im Hauptmenü anbieten. Da nächster Drink aber irgendwo hinten an einer Funktionalität hängt, gehört er hier eigentlich nicht rein. Die Abfrage mit dem Alkohol/ohne Alkohol baue ich noch ein. Ich brauche aber eine kurze Abstimmung, welche Version wir umsetzen:

Version 1
1. Frage Alkohol ja/nein
2. Frage ob Geschmack, Zutat oder egal
3. Vorschlag und Frage ob noch ein Vorschlag

Version 2
1. Frage ob Zutat/Geschmack/Alkohol
2. Wenn Zutat/Alkohol Frage ob Alkohol # Wenn  Alkohol keine weitere Nachfrage
3. Vorschlag

Ich bin für Variante 1.

**Comment by crownver** [comment]
Schließe mich Felix an, Version 1. 

Den Punkt bzgl. "Nächster Drink" haben wir gerade in der Vorlesung kurz diskutiert. Laut ihrer Aussage gehört dieser, wie Felix schon sagt, nicht dorthin. Meine Argumente haben sich also bestätigt und ich würde dich @RobinGrellner bitten, diesen Punkt zu entfernen.

**Comment by RobinGrellner** [comment]
Ok, in dem Fall wäre ich dann auch für Variante 1. 
Dann werde ich nun folgendes tun:
1. Den Ablauf des Anwendungsfalles "Drink ausgeben" ändern und die Extended UseCases entfernen
2. Die Abfrage beim löschen hinzufügen. 
3. Eine Email schreiben in der ich bezüglich des Vorkommens des Anwendungsfalles "nächster Drink" im Diagramm noch einmal nachfrage. Hier schicke ich ihr gleich den Prototypen mit.

**Comment by RobinGrellner** [comment]
So, Anwendungsfallbeschreibungen sind jetzt auch aktualisiert. In der Version gebe ich euch vollkommen recht: Nächster Drink fällt komplett weg. Ebenso fallen die Extends Fälle weg!
