### ISSUE TITLE
Sprint 0 - Product Backlog

### ISSUE THREAD

**Issue by crownver** [sweIhm-ws2018-19/skillproject-do-2#16]
Ein Product Backlog ist im GitHub Project, mittels GitHub Issues zu erstellen.

**Comment by Rybak07** [comment]
Im Project sind die Issues sortiert, allerdings kann man das innerhalb kürzester Zeit verändern, ohne dass jemand davon mitbekommt. Ich würde dieses Issue doch noch offen lassen und auch eine Datei mit dem Namen "ProductBacklog" ins Repo hochladen. Dort sind dann auch nochmal alle Anforderungen aufgelistet. Damit hätten wir es zwar doppelt, sind aber auf der sicheren Seite.

**Comment by Rybak07** [comment]
Das Product Backlog mit den Systemanforderung nach Priorität sortiert liegt jetzt im Repo. Die User Stories werden dann noch hinzugefügt sobald sie fertig sind.

**Comment by crownver** [comment]
![product_backlog](https://user-images.githubusercontent.com/38068315/48489620-c1ef8780-e823-11e8-807d-3c4793038762.png)

Meine überarbeitete Version.

**Comment by crownver** [comment]
Closed, wegen des Projects - Issue unnötig
