### ISSUE TITLE
Fachklassenmodell

### ISSUE THREAD

**Issue by crownver** [sweIhm-ws2018-19/skillproject-do-2#18]
Ein Fachklassenmodell, auch Analyseklassenmodell genannt, unseres Skills ist zu erarbeiten und soll anschließend hier und in der zugehörigen Ordnerstruktur eingefügt werden.

**Comment by Rybak07** [comment]
Hier der erste Ansatz für das Fachklassenmodell. Ein Tabelle mit Beschreibungen der einzelnen Klassen ist in Arbeit und wird hochgeladen sobald sie fertig ist. Bei der Kardinalität zwischen Anforderungsdecoder und Drinkliste bin ich mir noch nicht ganz sicher. Was meint ihr?

![Uploading Fachklassenmodell.png…]()

**Comment by fhaala** [comment]
Mir fehlen da spontan noch die Zutaten in irgendeiner Form.

**Comment by RobinGrellner** [comment]
Bei mir wird da ehrlich gesagt nichts angezeigt :3

**Comment by fhaala** [comment]
Stimmt, angezeigt wird nichts. Hab mor das File im Repo angeschaut. Wie gesagt, mir fehlt da noch bissl was und im Untrricht haben wir auch ein Modell gesehen, das aufwändiger war: wichtige Attribute und Methoden, keine Setter/Getter... Es ist ja nichts in Stein gemeißelt.

**Comment by Rybak07** [comment]
Tut mir leid im Buch steht es leider anders als heute in der Vorlesung erklärt. Ich werde es jetzt nochmal überarbeiten. Die Zutaten würde ich als ArrayList von Strings machen, weswegen jetzt hier auch keine Klasse für die Zutaten ist. Soll ich lieber eine Klasse dafür machen oder reicht eine ArrayList dafür?

Was die Anzeige betrifft: Es wurde leider gestern leider nicht mehr ins Issue geladen, aber es ist im Repo drinnen.

**Comment by fhaala** [comment]
Gefällt mir gut, muss aber leider ein paar Sachen anmerken: Daytime müssen wir nicht bei getRandomDrink übergeben - das Objekt ZEIT kann die Methode ja selbst für den Aufruf erzeugen und dann mit den enums des jeweiligen Drinks abgleichen. DeleteIngredient dürfte es als Methode nicht geben. Heißgeträng müsste noch richtig geschrieben werden. Bei Klasse Ingredient darf meines Erachtens der unterste Kasten weg. Category müsste inkl. Methoden komplett entfernt werden und dürfte nicht auftauchen, haben wir ja nicht. Bei allen random Drinks muss übergeben werden, ob Alkohol erlaubt ist oder nicht. Hat noch jemand Anmerkungen?

**Comment by Rybak07** [comment]
Also ich habe all deine Anmerkungen übernommen und selbst noch ein paar Dinge verbessert. Statt der ArrayList erscheint mir eine HashMap sinnvoller, da wir so nicht extra über die ganze Liste iterieren müssen um Änderungen an einem einzigen Drink vorzunehmen. Außerdem hab ich die Klasse Drink um das Attribut "daytime" erweitert und die entsprechende Methode in Drinks hinzugefügt.
<img width="871" alt="fachklassenmodell" src="https://user-images.githubusercontent.com/42803737/48440568-80aa9980-e789-11e8-979f-1fe8e713650d.png">

**Comment by Rybak07** [comment]
Ich habe die Verbesserungsvorschläge im Feedback auf Moodle in das Fachklassenmodell eingebracht.
Während Sprint1 werden aber noch einige Änderungen folgen.
<img width="595" alt="fachklassen" src="https://user-images.githubusercontent.com/42803737/48660848-f30cc980-ea68-11e8-87cb-c2f62a6b29b1.png">

**Comment by crownver** [comment]
Respekt, sieht wirklich Klasse aus!
