### ISSUE TITLE
Daily Scrum

### ISSUE THREAD

**Issue by crownver** [sweIhm-ws2018-19/skillproject-do-2#19]
Hier bitte jeden Tag von **jedem** ein kurzes Update was er an diesem Tag gemacht hat bzgl. Softwareengineering. Das Update ist spätestens um 20.00Uhr einzutragen und wir im darauffolgenden Tag in das Wiki übernommen.

Zusammenfassung: [https://github.com/sweIhm-ws2018-19/skillproject-do-2/wiki/Daily-Scrum](https://github.com/sweIhm-ws2018-19/skillproject-do-2/wiki/Daily-Scrum)

**Comment by crownver** [comment]
Nachtrag zu gestern - Meeting zur Besprechung der weiteren Vorgehensweise und der endgültigen Arbeitsaufteilung.

**Comment by fhaala** [comment]
Nachtrag zu gestern: /

**Comment by Rybak07** [comment]
Nachtrag zu gestern: /

**Comment by RobinGrellner** [comment]
07.11.
Erarbeiten von Anwendungsfallbeschreibungen und, -diagrammen. 
Zusätzliche Frage zur Gliederung in System- und Geschäftsanwendungsfälle (Wir müssen nur die Systemanwendunsfälle behandeln).

**Comment by crownver** [comment]
8.11 

- Erarbeitung mehrerer Änderungen an der Idee (im Team)
- Abklärung besagter Idee durch Fr. Socher
- Änderungen am Wiki (Hauptaugenmerk auf die Systemidee, Beispiele hierzu)
- Wiki erweitert um alle nötigen Punkt & Entfernung des alten Prototyps
- Erstellung einer neuen Ordnerstruktur

Information für @fhaala @Rybak07 @RobinGrellner 
**Alle im Laufe des Sprints erstellten Dateien werden unter [https://github.com/sweIhm-ws2018-19/skillproject-do-2/tree/master/Alexa-Skill/Sprint_0](https://github.com/sweIhm-ws2018-19/skillproject-do-2/tree/master/Alexa-Skill/Sprint_0) gespeichert und tragen einen eindeutigen Namen.
Es sind keine verschiedenen Versionen zu speichern!**

**Comment by fhaala** [comment]
8.11.
App-Idee im Team überarbeitet

**Comment by RobinGrellner** [comment]
08.11.
/

**Comment by Rybak07** [comment]
08.11.
/

**Comment by fhaala** [comment]
08.11.2019: /

**Comment by fhaala** [comment]
10.11.2019: /

**Comment by fhaala** [comment]
11.11.2019: User Stories erstellt.

**Comment by RobinGrellner** [comment]
09.11.2019
/

**Comment by RobinGrellner** [comment]
10.11.2019 
Erstellen des Anwendungsfalldiagramms sowie folgender Anwendungsfallbeschreibungen:
Begrüßung, Drink eingeben, Drink löschen, Favorit festlegen, Favorit abrufen, Zutaten abfragen, Drink vorschlagen(Dazu auch die jeweiligen ausprägungen), Hilfe verlangen

**Comment by crownver** [comment]
9/10/11.11: /

**Comment by Rybak07** [comment]
9/10/11.11.2018: /

12.11.2018:
Product Backlog als neues Project hinzugefügt.
Erster Ansatz für das Fachklassenmodell.

**Comment by fhaala** [comment]
12.11.2018: User Stories + Prototyp überarbeitet, Product Backlog / Anwendungsfalldiagramm / Anwendungsfälle / Fachklassenmodell kommentiert

**Comment by crownver** [comment]
12.11.18: 
Prototyp überarbeitet und getestet 
Kommentierung der Issues 
Genauere Ausarbeitung der Systemidee

**Comment by crownver** [comment]
13.11.18: /

**Comment by fhaala** [comment]
13.11.2018: User Stories + Prototyp überarbeitet + Hilfestellungen

**Comment by crownver** [comment]
14.11.18: 
Finale Bearbeitung des Wiki
Einfügen einer neuen Sidebar ins Wiki
Neue Aufteilung im Wiki
Kleine Änderungen an der Systemidee (Formulierung)

**Comment by RobinGrellner** [comment]
11.11.2018
Realisierung weiterer Anwendungsfälle

**Comment by RobinGrellner** [comment]
12.11.2018
/

**Comment by RobinGrellner** [comment]
13.11.2018
Finale bearbeitung der Anwendungsfallbeschreibungen, sowie des zugehörigen Diagramms.

**Comment by fhaala** [comment]
Heute 25+ Drinks, teilweise mit Zutaten, eingegeben und in Json umgewandelt. Maven Projektfiles angepasst, Dependencies eingegeben und Travis CI gecheckt.

**Comment by RobinGrellner** [comment]
So, auf Anfrage habe ich mal den Daily Scrum hiermit wiederbelebt. Bitte tägliche updates wie es bei euch läuft, falls etwas vergessen wird, am besten einfach den gewohnten / schreiben.

**Comment by RobinGrellner** [comment]
04.012.
@fhaala und ich saßen heute wieder einige Zeit an dem Skill. 
Wir haben nun eine ziemlich gute Idee von der Strukturierung und der Implementierung von Drink eingeben. 
Wir haben die Funktion zwar noch nicht zum laufen gebracht, aber wir wissen wo die Fehler liegen und haben schon ein paar lösungsansätze gefunden.
Sprich: diese Funktion sollte bald lauffähig sein. 

Was wir sonst noch überarbeiten müssten wären die Dialoge, bzw die Response messages. 

Für mich sind auch noch einige Fragen offen: 
-Müssen die Handler bis zum nächsten mal getestet sein?
- Gibt es jemanden der gerne die Aufgabe der Dialogentwicklung übernehmen würde? (Zu diealog gehören Reprompt messages, Responses, Samples)

Falls es rückfragen gibt stehe ich für diese gerne zur Verfügung.

**Comment by RobinGrellner** [comment]
05.12.
Es gibt eine gute und eine schlechte Nachricht.
Die gute ist: Logik und implementierung haben wir verstanden und können dies anwenden.
Die schlechte: Unsere App-Idee ist so scheinbar nicht umsetzbar.

Ich würde vorschlagen @fhaala und ich fragen morgen diesbezüglich nach, da wir die sind, die am meisten in den Code eingearbeitet sind.

Das wäre alles von @fhaala und von mir für heute.

**Comment by crownver** [comment]
5.12 
- Übernahme der Hilfe-Peogrammierung 
- Änderung zweier Dialoge 
- Issues

**Comment by crownver** [comment]
6.12 - Allgemein
- Neues Planning-Meeting
- Entfernen der Funktionen "Drink löschen" und "Drink eingeben"
- Hinzufügen der Funktion "Rezept abfragen" (+ User Story usw.)
- Änderungen an Wiki, Issues, ...
