### ISSUE TITLE
Übungsblatt KlassenObjektDiagramme Aufgabe 4 [Assignee: Xaver Siodlazek] [Reviewer: Robin Grellner, Alexander Heinritzi]

### ISSUE THREAD

**Issue by fhaala** [sweIhm-ws2018-19/skillproject-do-2#2]
Hier diskutieren wir die Lösung zu oben genannter Aufgabe. Anbei der zugehörige Ausschnitt aus der Angabe. Der Code befindet sich unter: https://github.com/sweIhm-ws2018-19/skillproject-do-2/tree/master/UML/objektdiagramm

![bildschirmfoto 2018-10-18 um 14 41 11](https://user-images.githubusercontent.com/43846490/47154905-e53a1c00-d2e3-11e8-8d37-fb11178e5bab.png)

**Comment by crownver** [comment]
![objektdiagramm](https://user-images.githubusercontent.com/38068315/47169207-33124c80-d303-11e8-9a39-96dc839e5e5f.png)

Anbei ein Bild der Bearbeitung. Die Datei, welche in draw.io geladen werden muss, wird hier leider nicht unterstützt, deswegen anbei ein zip:

[Objektdiagramm(1).zip](https://github.com/sweIhm-ws2018-19/skillproject-do-2/files/2492764/Objektdiagramm.1.zip)

**Comment by crownver** [comment]
Zum ersten Punkt - ich verstehe nicht ganz was du meinst, es gibt nur die Klassen Konto, Kunde, Privatkunde, Geschäftskunde und Adresse, könntest du das Problem bitte spezifizieren und einen konkreten Vorschlag machen?

Welche Vorlage? Bitte Bild und Seitenzahl. Ich habe die Vorlage aus dem Einband benutzt, also sozusagen Seite 1. Dort "attribut = wert".

Umlaute ändere ich natürlich.

**Comment by crownver** [comment]
Bezüglich den Umlauten. draw.io kann diese problemlos darstellen, deshalb würde ich diese auch so drinnen lassen. Wenn es andere Meinungen gibt, dann sagt es mir bitte.

**Comment by fhaala** [comment]
1. Du hast nur Kunden und Adressen dargestellt, die Objekte der Konten fehlen komplett in dem Bild.
2. Auf Seite 227 findest du Beispiele, die sind komplett ohne Leerzeichen.
3. Ich wegen Einheitlichkeit bei den Klassennamen und Attributen ohne Umlaute schreiben. Die Strings dürfen natürlich trotzdem Umlaute tragen!

**Comment by Rybak07** [comment]
Dem schließe ich mich an. Es ist besser wenn wir es bezüglich der Umlaute einheitlich machen.
Konten würde ich auch noch hinzufügen. Einmal mit der Bezeichnung "Geschäftskonto" für das Objekt der Klasse "Geschäftskunde" und einmal mit der Bezeichnung Privatkonto das Objekt der Klasse Privatkunde.

**Comment by fhaala** [comment]
Ja, wobei die Bezeichnung "geschaeftskonto" und "privatkonto" wäre. Datentyp wäre dann jeweils "Konto".

**Comment by crownver** [comment]
1. Gut, die Änderungen versuche ich umzusetzen. Ich stelle dann ein Bild des Ergebnisses hier rein bevor ich neu hochlade. 
2. Gut, da aber da anscheinend sogar das Buch nicht eindeutig ist würde ich abstimmen. Ich persönlich finde es schöner mit Leerzeichen. 
3. Gut, dann bleiben die Strings so und den Rest ändere ich.

**Comment by fhaala** [comment]
1. Sehr gut.
2. Im Eiband steht es allgemein mit, aber in allen Beispielen dann ohne. Daher bin ich für "ohne".
3. Top!

**Comment by crownver** [comment]
![objektdiagramm_neu](https://user-images.githubusercontent.com/38068315/47254536-13df0080-d464-11e8-9273-147563a413d7.png)

**Comment by fhaala** [comment]
Bitte oben bei den beiden Konten nicht privat"kunde" oder geschaefts"kunde" sondern "konto" verwenden, da es ja ein Konto beschreibt. Natürlich ist das dann mit der Bezeichnung redundant, aber ich weiß nicht was Bezeichnung sonst noch für einen Sinn hätte.

Bei hansMueller:Geschaeftskunde musst du auch noch den Objektnamen anpassen.

**Comment by crownver** [comment]
Der Objektname war jetzt absichtlich noch so, da die Klasse in der Angabe "Geschäftskunde" heißt aber ich werds ändern.

**Comment by crownver** [comment]
![grafik](https://user-images.githubusercontent.com/38068315/47254940-fceedd00-d468-11e8-9788-354a34b31170.png)

**Comment by fhaala** [comment]
So sieht das für mich ganz gut aus. Was sagt der Rest?

**Comment by RobinGrellner** [comment]
An sich sieht es für mich auch schon sehr gut aus. Nur eine Frage hätte ich bezüglich der Umlaute in den Strings, sind diese okay? Es kommt ja theoretisch auf die Codierung des Programms an ob er diese Interpretieren kann oder nicht, meint ihr wir müssen uns darum kümmern ob UTF-8 oder ASCII genutzt wird?

**Comment by fhaala** [comment]
Ich bin unsicher, vermute aber, dass das zwei Paar Stiefel sind. Kann kurz jemand Testprogramm schreiben? Aber unabhängig davon: ich bin der Meinung, dass es im Code nichts zu suchen hat, da der einfach international und am Besten sowieso englisch ist. Der Inhalt muss aber sehr wohl regional funktionieren, also mit Umlauten.

**Comment by Rybak07** [comment]
Nachdem wir vorhin gesagt haben wir wollen es einheitlich, also kein ä,ö oder ü, sollten diese meiner Meinung auch nicht in den Strings enthalten sein.

**Comment by crownver** [comment]
Einen Attributnamen zu verändern und zu verallgemeinern bzgl. Umlauten finde ich geht aber der String hat ja eine eindeutige Bedeutung und wurde uns genauso gegeben. Wenn jemand im Nachhinein nach einem Herrn Müller suchen würde, den es ja geben müsste, würde er ihn bei uns nicht finden - ich persönlich möchte das nicht ändern. 
Falls jedoch die Allgemeinheit dafür ist werde ich mich beugen aber keine Verantwortung dafür übernehmen.

**Comment by fhaala** [comment]
Wie oben schon erwähnt, bin da eher bei Xaver. Der Müller heißt Müller, und das muss das Programm auch so wiedergeben können. Der Code dazu ist intern aber international und da gibt es halt keine Umlaute.

**Comment by RobinGrellner** [comment]
Dann schließe ich mich da eher der Meinung von Felix und Xaver an, da ein solches Programm ja regional Funktionieren soll, sollte es auch mit Umlauten und sonstigen Sonderziechen umgehen können. 
Sprich: Von meiner Seite aus gibt es nichts auszusetzen

**Comment by Rybak07** [comment]
Nachdem ihr alle der Meinung seid der selben Meinung seid, ist es für mich auch ok wenn wir es so lassen wie es jetzt ist.

**Comment by crownver** [comment]
Gut, da das jetzt geklärt ist, hier das finale Ergebnis. 
![objektdiagramm](https://user-images.githubusercontent.com/38068315/47265277-c5923600-d525-11e8-93cf-596895af5583.png)

Damit schließe ich auch das Issue.
