### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by crownver** [sweIhm-ws2018-19/skillproject-do-2#21]
Diskussionsfeld für die Auswahl eines Logos.

**Comment by crownver** [comment]
![skizze 4](https://user-images.githubusercontent.com/38068315/48347564-e2caa800-e67e-11e8-8537-eb4605435c1b.png)
![skizze 5](https://user-images.githubusercontent.com/38068315/48347565-e3633e80-e67e-11e8-9716-77451c3b12f0.png)
![skizze 6](https://user-images.githubusercontent.com/38068315/48347567-e3633e80-e67e-11e8-8a74-f5b92d9c9d00.png)
![skizze 7](https://user-images.githubusercontent.com/38068315/48347568-e3633e80-e67e-11e8-8286-3ccc3780fb16.png)
![skizze 1](https://user-images.githubusercontent.com/38068315/48347569-e3fbd500-e67e-11e8-857d-533692ca53cc.png)
![skizze 2](https://user-images.githubusercontent.com/38068315/48347570-e3fbd500-e67e-11e8-881a-e9008467923e.png)
![skizze 3](https://user-images.githubusercontent.com/38068315/48347571-e4946b80-e67e-11e8-958a-aacff0d55f01.png)

Hier meine Entwürfe.

**Comment by Rybak07** [comment]
Mir gefällt das zweite von Oben am besten. Das finde ich auch sehr gut.

**Comment by fhaala** [comment]
Habe vorhin das zweite einfach mal zur Demo hinzugefügt. Anscheinend sind wir uns ja einig?

**Comment by RobinGrellner** [comment]
Jep, 2. von oben finde ich auch am ansprechensten!
