### ISSUE TITLE
Begrüßung

### ISSUE THREAD

**Issue by Rybak07** [sweIhm-ws2018-19/skillproject-do-2#22]
User Story:

Als User möchte ich den Simple Barkeeper einfach per Zuruf starten können und von ihm begrüßt werden, um das Gefühl eines Gesprächs zu bekommen.

Akzeptanzkriterien:

⦁	Nutzer startet SB mit Sprachbefehl "Alexa starte Simple Barkeeper".
⦁	SB begrüßt Nutzer, um Kontakt aufzubauen und Eingabe zu bestätigen.

**Comment by RobinGrellner** [comment]
Initialversion der Begrüßung/ des LaunchRequestHandlers ist erstellt.
Alexa begrüßt unseren Gast mit "Hallo. Wie kann ich dir behilflich sein?".
Falls keine Eingabe seitens des Users erfolgen sollte, so geben wir ihm mit "Falls du Hilfe brauchst, sag einfach 'Hilf mir'" einen kleinen Anstoß.

**Comment by RobinGrellner** [comment]
Keine Änderung, aber da der Skill nun lauffähig ist, und sich die Responses nicht verändert haben schließe ich das Issue nun.

**Comment by crownver** [comment]
Setzung des Labels "ready for review" im Namen des Autors.
Überprüfung durch @crownver und @RobinGrellner.

**Comment by crownver** [comment]
Geprüft @crownver

**Comment by RobinGrellner** [comment]
Geprüft @RobinGrellner .
