### ISSUE TITLE
Drink Eingeben

### ISSUE THREAD

**Issue by Rybak07** [sweIhm-ws2018-19/skillproject-do-2#23]
User Story:

Als User möchte ich dem Simple Barkeeper eigene Drinks inkl. Zutaten hinzufügen können, um sie mir nicht merken zu müssen, sie später abfragen zu können und den Drink vorgeschlagen zu bekommen.

Akzeptanzkriterien:

⦁	User ruft Funktion durch Ausspruch von "Drink eingeben" auf.
⦁	Nutzer kann eigene Drinks hinzufügen.
⦁	Drinkname wird vom Nutzer eingegeben und vom SB als Bestätigung widerholt, sowie Korrektheit       durch Nutzer geprüft.
⦁	Bei Fehler erfolgt Neueingabe.
⦁	Jede Zutat und zugehörige Menge werden einzeln abgefragt, vom SB widerholt und auf Korrektheit vom Nutzer überprüft.
⦁	Bei Fehler erfolgt Neueingabe.
⦁	Nach jeder Zutat wird gefragt, ob weitere Zutat eingegeben werden soll.
⦁	Falls ja, wiederholt sich dieser Block.
⦁	Falls nicht, wird bestätigt, dass Drink gespeichert wurde,
⦁	Möglichkeit abzubrechen und in Hauptmenü zurückzukehren.

**Comment by RobinGrellner** [comment]
Nachdem wir (@fhaala und @RobinGrellner ) die Logik implementiert und verstanden haben, ist uns ein riesiges Problem aufgefallen.

Und zwar haben wir erfahren, dass Freitexteingaben bei Alexa nicht wirklich möglich sind. 
Das einzige was möglich ist, jedoch unglaubliches Fehlerpotenzial hat, ist die Eingabe einzelner Wörter. 
Dies kommt daher, dass er immer mit den Slots gegenprüft. Nach einiger Recherche habe ich nun auch herausgefunden, dass Alexa eine Art Mapping nutzt, die diese Slots als Referenz nutzt und in speziellen Fällen auch mal gerne ein ähnliches Wort ummapt. Dies kann speziell für uns zu massiven Fehlern führen, da Freitexteingaben so nicht mehr wirklich frei sind, sondern immernoch supervised und gegen den Willen des Users manipuliert werden können. 
Hier gibt es so gesehen zwei "Alternativen" wie man das umsetzen könnte. 
1. Man speichert eine Liste mit allen Wörtern dieser Welt, bzw. allen Buschtabenkombinationen als Slotliste ab. Dies ist denkbar unrealistisch.
2. Man "trainiert Alexa" mit Datensätzen (laut Forenbeiträgen in developer.amazon.de sind 3000 nicht annähernd genug um eine genaue Eingabe zu erkennen), die sie nutzt um künftige User eingaben zu erkennen. Ebenfalls keine valide Möglichkeit in meinen Augen.

Daher würde ich gerne bald möglichst mit Prof. Socher besprechen., wie wir weiter vorgehen sollen. 
Eine Alternative wäre hier, die beiden Funktionen "Drink eingeben" und "Drink löschen" zu entfernen, bzw umzustrukturieren. 
Dies ist natürlich denkbar zeitaufwendig und eigentlich auch nicht wirklich eine zufriedenstellende Option.

**Comment by crownver** [comment]
Schließung wegen des "Crashs".
Keine weitere Implementierung vorgesehen.
