### ISSUE TITLE
Drink löschen

### ISSUE THREAD

**Issue by Rybak07** [sweIhm-ws2018-19/skillproject-do-2#24]
User Story:

Als User möchte ich nicht mehr benötigte Drinks (inkl. Zutaten) aus dem Simple Barkeeper löschen können, um sie nicht mehr vorgeschlagen zu bekommen.

Akzeptanzkriterien:

⦁	User ruft Funktion durch Ausspruch "Drink löschen" auf.
⦁	Drinkname wird vom Nutzer genannt.
⦁	SB widerholt den Namen und prüft somit ob der richtige Drink erkannt wurde.
⦁	Nach Ja/Nein Antwort des Nutzers wird entsprechender Drink gelöscht oder Abfrage widerholt.
⦁	Abschließende Bestätigung der Löschung.
⦁	Möglichkeit abzubrechen und in Hauptmenü zurückzukehren.

**Comment by fhaala** [comment]
Implementiert aber ungetestet

**Comment by crownver** [comment]
Schließung bzgl. des "Crashs". 
Keine weitere Implementierung vorgesehen.
