### ISSUE TITLE
Favoriten festlegen

### ISSUE THREAD

**Issue by Rybak07** [sweIhm-ws2018-19/skillproject-do-2#25]
User Story:

Als User möchte ich im Simple Barkeeper einen Drink als Favoriten festlegen können, um ihn später ohne namentliche Nennung abrufen zu können bzw. mir den Namen nicht merken zu müssen.

Akzeptanzkriterien:

⦁	User ruft Funktion durch den Ausspruch "Favoriten festlegen" auf.
⦁	Name des Favoriten wird vom SB abgefragt.
⦁	Falls Getränk vorhanden wird Name widerholt Bestätigung vom Nutzer eingeholt, dass er richtig verstanden wurde.
⦁	Falls ja, wird Favorit gespeichert und eine Meldung diesbezüglich ausgegeben.
⦁	Falls nein, wird Block widerholt.
⦁	Möglichkeit abzubrechen und in Hauptmenü zurückzukehren.

**Comment by fhaala** [comment]
Nötiger Java-Code wurde erstellt und getestet. Handler fehlen noch.
