### ISSUE TITLE
Favorit abrufen

### ISSUE THREAD

**Issue by Rybak07** [sweIhm-ws2018-19/skillproject-do-2#26]
User Story:

Als User möchte ich im Simple Barkeeper einen festgelegten Drink, den Favoriten, ohne namentliche Nennung abrufen können, um nicht über den exakten Namen nachdenken zu müssen oder ihn mir zu merken.

Akzeptanzkriterien:

⦁	User sagt "Favorit abrufen" und erhält als Antwort vom SB den Namen des Drinks.
⦁	Fehlermeldung, falls zuvor kein Drink festgelegt wurde.
⦁	Möglichkeit abzubrechen und in Hauptmenü zurückzukehren.

**Comment by fhaala** [comment]
Nötiger Java-Code wurde erstellt und getestet. Handler fehlen noch.
