### ISSUE TITLE
Zutaten abfragen

### ISSUE THREAD

**Issue by Rybak07** [sweIhm-ws2018-19/skillproject-do-2#27]
User Story:

Als User möchte ich vom Simple Barkeeper die Zutaten eines bestimmten Drinks abfragen können, um ihn mir zuzubereiten.

Akzeptanzkriterien:

⦁	User sagt "Zutaten abfragen" wird vom SB nach dem Getränkenamen/Favoriten gefragt.
⦁	Je nach Auswahl erhält der User vom SB als Antwort eine Liste von Zutaten und zugehörigen Mengen.
⦁	Ist kein Favorit festgelegt oder Drink nicht vorhanden, erfolgt Fehlermeldung durch SB.
⦁	Möglichkeit abzubrechen und in Hauptmenü zurückzukehren.

**Comment by Rybak07** [comment]
Die Methode der Klasse Drink, die die Zutaten als String wieder gibt (listIngredients) ist fertig und getestet.

**Comment by RobinGrellner** [comment]
Der Handler für den ListIngrediensIntent ist nun fertig geschrieben und Lauffähig. 
In diesem Intent wird nun eine Liste initialisiert, die @fhaala Implementiert hat. Mit dieser wird der vom input aufgefangene Drink verglichen und durch eine von @Rybak07 geschriebene Methode die Zutaten ausgegeben. 
Da auch dieser Intent lauffähig ist und funktioniert kann das Issue nun geschlossen werden

**Comment by crownver** [comment]
Setzung des Labels "ready for review" im Namen des Autors. 
Überprüfung durch @crownver und @RobinGrellner.

**Comment by crownver** [comment]
Geprüft @crownver

**Comment by RobinGrellner** [comment]
Geprüft @RobinGrellner.

**Comment by fhaala** [comment]
Nötiger Java Code ist umgesetzt und getestet. Handler wurden von Robin schon eingebunden, müssen aber noch getestet werden.

**Comment by crownver** [comment]
Code wurde mir von @fhaala erklärt und durch mich geprüft.
