### ISSUE TITLE
Drink vorschlagen

### ISSUE THREAD

**Issue by Rybak07** [sweIhm-ws2018-19/skillproject-do-2#28]
User Story:

Als User möchte ich vom Simple Barkeeper tageszeitabhängig einen Drink vorgeschlagen bekommen - anhand einer genannten Zutat, eines Geschmacks oder per Zufall und unter der Angabe ob Alkohol erwünscht ist. Ich will mir keine eigenen Gedanken zu einem Getränkewunsch machen und eventuell vorhandene Zutaten aufzubrauchen.

Akzeptanzkriterien:

⦁ User ruft Funktion per Ausruf "Drink vorschlagen auf" und wird vom SB gefragt, ob Alkohol erlaubt ist.
⦁Nach seiner Antwort wird er vom SB gefragt, ob nach Zutat/Geschmack/Zufall.
⦁ Bei der Wahl "Zutat" wird vom SB eine gewünschte Zutat erfragt, bei der Wahl "Geschmack" ein Geschmack. Bei Zufall wird random ausgewählt.
⦁User nennt Zutat/Geschmack und erhält, angepasst an die Tageszeit, einen entsprechenden Vorschlag vom SB (Drinkname).
⦁Danach erfolgt Frage, ob weiterer Vorschlag erfolgen soll.
⦁Falls ja, neuer Vorschlag nach bekannten Vorgaben.
⦁Falls nein, Rückkehr zum Hauptmenü.
⦁Möglichkeit abzubrechen und in Hauptmenü zurückzukehren.

**Comment by crownver** [comment]
@Rybak07, User Story muss verändert werden, da die Uhrzeit als Parameter keine Rolle mehr spielt.

**Comment by crownver** [comment]
Die Zeit ist kein Bestandteil mehr des „Drink vorschlagen“.

**Comment by fhaala** [comment]
Die nötigen Java Methoden wurden bereits erstellt und getestet. Es fehlen noch die Handler.
