### ISSUE TITLE
Übungsblatt UseCaseAktivitaetSequenzDiagramme Aufgabe 1 [Reviewer: Felix Haala, Robin Grellner, Xaver Siodlazek]

### ISSUE THREAD

**Issue by crownver** [sweIhm-ws2018-19/skillproject-do-2#3]
Hier diskutieren wir die Lösung zu oben genannter Aufgabe. Die Aufgabenstellung anbei.

![grafik](https://user-images.githubusercontent.com/38068315/47493868-a01c6980-d850-11e8-8b95-e3dcd60c85ef.png)

**Comment by Rybak07** [comment]
Hier mein Lösungsvorschlag für die Aufgabe 1.
<img width="398" alt="blatt 2 aufgabe 1" src="https://user-images.githubusercontent.com/42803737/47496163-50d93780-d856-11e8-9e0a-b032ec70d072.png">

**Comment by crownver** [comment]
Bitte auch in ".../UML/Uebung_2/Aufgabe_1 auch eintragen.

**Comment by crownver** [comment]
Nur eine Überlegung, aber sollte der "Actor" nicht "User" heißen?
Des Weiteren sollten sich die Striche beim User nicht treffen, siehe Ausschnitt aus den Folien.
![grafik](https://user-images.githubusercontent.com/38068315/47573532-da176980-d93d-11e8-9e8a-62c70eb325c4.png)

**Comment by fhaala** [comment]
Ich gebe Xaver recht. Die Linien sollten sich nicht berühren. Der Typ sollte User heißen. Bitte auch exakt die Beschriftung aus der Angabe noch einmal in die Ellipsen kopieren - da sind hier ein paar Beschreibungen abgekürzt oder die Reihenfolge nicht eingehalten (ein/aus/...). Fällst sonst noch jemandem was auf?

**Comment by Rybak07** [comment]
Ich habe ihn jetzt zu User umbenannt und die Beschriftungen aus der Aufgabe kopiert. Allerdings denke ich nicht, dass die Linien sich nicht berühren dürfen. In einem Lösungshinweis auf dem Blatt (Aufgabe 3) berühren sich diese Linien in einem anderen Anwendungsfalldiagramm. Ich kann dies auf Wunsch aber trotzdem noch ändern. Den nächsten Lösungsvorschlag lade ich hoch sobald wir das entschieden haben.

**Comment by fhaala** [comment]
Wenn du ein offizielles Beispiel hast, das wir in der Vorlesung bekommen haben und als Referenz bei "falscher" Korrektur nehmen können, ist das auch in Ordnung. Ansonsten hätte ich mich eben lieber auf die Beispiele im Buch bezogen.

**Comment by Rybak07** [comment]
Hier mein neuer Lösungsvorschlag. Wenn das so passt würde ich das Issue schließen.
<img width="290" alt="aufgabe_1" src="https://user-images.githubusercontent.com/42803737/47745884-07894d80-dc85-11e8-87b5-79cc3b7e8a53.png">

**Comment by fhaala** [comment]
Passt für mich.
