### ISSUE TITLE
Hilfe verlangen

### ISSUE THREAD

**Issue by Rybak07** [sweIhm-ws2018-19/skillproject-do-2#31]
User Story:

Als User möchte ich vom Simple Barkeeper erfahren, welche Optionen mir zur Verfügung stehen um ihn richtig verwenden zu können.

Akzeptanzkriterien:

Die Hilfe muss alle möglichen Befehle aus dem "Hauptmenü" auflisten. Nach Nennung eines Punktes muss dieser kurz erklärt werden.

**Comment by crownver** [comment]
Es soll eine Hilfe geben, welche im Hauptmenü die verfügbaren Möglichkeiten auflistet und ggf. zu diesen auch genauere Informationen von sich gibt (auf Nachfrage). 
Das ganze kann/soll mit einem Beispiel begleitet werden (auf Nachfrage).
In den jeweiligen Verzweigungen wie z.B. „Drink eingeben“, soll es auch einen Hilfeaufruf geben, welcher den derzeitigen Punkt genauer erklärt und auch auf Nachfrage ein Beispiel liefert.

**Comment by crownver** [comment]
Die User-Story ist gegeben der neuen Anforderungen anzupassen. 
Diese Aufgabe, sowie die Implementierung der Hilfen wurde @Rybak07 zugeteilt.

**Comment by crownver** [comment]
1. Die Zuteilung hat sich von @Rybak07 auf @crownver geändert. 

2. In den jeweiligen Verzweigungen ist es nicht immer möglich ein Hilfe-Menü zu gestalten. Beim Abfragen eines Drinks folgt entweder die Ausgabe der Zutaten oder aber ein Abbruch. In beiden Fällen gibt es keine Möglichkeit innerhalb des Intents eine Hilfe aufzurufen.
Die Hilfe-Menüs, welche also innerhalb der Intents aufgerufen werden können sollen, beschränken sich auf: 

- Drink eingeben
- Drink vorschlagen 

Die Implementation in Drink eingeben wird in diesem Sprint (Sprint 2) erfolgen, sofern möglich. 

3. Die allgemeine Hilfe wurde überarbeitet (textuell gesehen)

**Comment by crownver** [comment]
Code wurde @Rybak07 von @RobinGrellner erklärt und durch  @Rybak07 geprüft.
