### ISSUE TITLE
Nächster Drink

### ISSUE THREAD

**Issue by Rybak07** [sweIhm-ws2018-19/skillproject-do-2#32]
User Stroy:

Als User möchte ich zu jedem Vorschlag die Möglichkeit haben, einen weitere Vorschlag zu erhalten um eine Auswahl zu erhalten bzw. so lange auszuwählen, bis mir ein Ergebnis zusagt.

Akzeptanzkriterien:

⦁	Nach jedem Vorschlag lässt sich ein weiterer Vorschlag nach den anfänglich gewählten Kriterien per Zufall ausgeben
⦁	Nach jedem Vorschlag wird abgefragt, ob ein weiterer erfolgen soll.
⦁	Soll kein weiter Vorschlag erfolgen, wird automatisch in das Hauptmenü zurückgekehrt.

**Comment by crownver** [comment]
Die Use Cases sind nicht aktuell. Dieser Punkt wurde schon entfernt, jedoch gab es gestern beim hochladen leider ein Problem. Felix kümmert sich drum.
