### ISSUE TITLE
Barkeeper schließen

### ISSUE THREAD

**Issue by Rybak07** [sweIhm-ws2018-19/skillproject-do-2#33]
User Stroy:

Als User möchte ich den Simple Barkeeper auf Zuruf schließen können um das Gespräch zu beenden.

Akzeptanzkriterien:

⦁	Der SB wird durch den Ausruf "Beenden" beendet.
⦁	Der SB verabschiedet sich wie ein Gesprächspartner vom User.

**Comment by RobinGrellner** [comment]
Initialversion des Handlers zum schließen ist erstellt. Zum abschied sagt dieser "Beehren sie uns bald wieder" und zeigt in einer Card der companion app selbiges mit dem Titel "Bar geschlossen" an.

**Comment by RobinGrellner** [comment]
Der Intenthandler für Cancel- und StopIntent sind im CancelandStopIntentHandler implementiert und lauffähig. Die Verabschiedung hat sich nicht verändert, weswegen das Issue nun geschlossen wird.

**Comment by crownver** [comment]
Setzung des Labels "ready for review" im Namen des Autors.
Überprüfung durch @crownver und @RobinGrellner.

**Comment by crownver** [comment]
Geprüft @crownver

**Comment by RobinGrellner** [comment]
Geprüft @RobinGrellner .
