### ISSUE TITLE
Programmierung - Drink-Liste

### ISSUE THREAD

**Issue by crownver** [sweIhm-ws2018-19/skillproject-do-2#35]
Als User möchte ich eine Vorauswahl an Drinks mitgeliefert bekommen, damit ich zum Ausprobieren der Anwendung nicht erst verschiedene rezepte eingeben muss, sondern sofort loslegen kann.

Akzeptanzkriterien:
- 20 Rezepte
- Automatischer Import der Rezepte beim ersten Start

**Comment by fhaala** [comment]
Der Converter Textbasierte Datei -> Drink-Objekte funktioniert schon einmal und liegt im Repository.

**Comment by fhaala** [comment]
Liste kann jetzt textbasiert erstellt, in Objekte umgewandelt und als Json ausgegeben werden. Json kann eingelesen und in Objekte umgewandelt werden.

**Comment by fhaala** [comment]
Heute 25+ Drinks, teilweise mit Zutaten, eingegeben und in Json umgewandelt.

**Comment by crownver** [comment]
Setzung des Labels "ready for review" im Namen des Autors.
Überprüfung durch @crownver und @RobinGrellner.

**Comment by crownver** [comment]
Geprüft @crownver

**Comment by RobinGrellner** [comment]
Geprüft @RobinGrellner .
