### ISSUE TITLE
Programmier Konventionen

### ISSUE THREAD

**Issue by crownver** [sweIhm-ws2018-19/skillproject-do-2#39]
Hier alle Konventionen.

**Comment by RobinGrellner** [comment]
Konvention package name:
alle packages sollen mit barkeeper."Paketname" benannt werden

**Comment by fhaala** [comment]
1. Application-Klasse erstellen - diese beinhaltet
			Package: baarkeeper
			Begrüßung
			Flag, ob schon gestartet wurde
			Import der mitgelieferten Rezepte
			
	2. Mitgleieferte Rezepte werden als Textdatei geliefert
			Pro Zeile ein String
			Aufbau:	1. Attribut name
							2. Attribut falvour
							3. Attribut daytime
							4. Attribut containsAlcohol
							5. String: --Ingredients--
							6. Zutat 1
							7. Zutat 1 Menge
							8. Zutat 2
							9. Zutat 2 Menge
							...
							X. String: --Next--

**Comment by RobinGrellner** [comment]
Intent handler kommen, mit der Ausnahme  SimpleBarkeeperStreamHandler, in das main.java.handler package.

**Comment by fhaala** [comment]
Aufbau Textdatei aktualisiert:
1. Attribut name
2. Attribut falvour
3. Attribut daytime
4. Attribut containsAlcohol
5. Attribut Ingredients
5. String: --Steps--
6. Step 1...
7. Step 2...
...
X. String: --Next--

**Comment by fhaala** [comment]
C-Tor erhält nun die Ingredients als einfachen String und die Steps als List of Strings.
