### ISSUE TITLE
Programmierung - Applikation 

### ISSUE THREAD

**Issue by crownver** [sweIhm-ws2018-19/skillproject-do-2#40]
Applikation, welche Folgendes beinhaltet:
- Begrüßung 
- Flag, ob der Skill schon einmal gestartet wurde
- Import der mitgelieferten Rezepte

**Comment by RobinGrellner** [comment]
Da die Logik nicht durch eine eigene Applikationsklasse implementiert werden muss fällt die Implementierung einer solchen weg.

**Comment by crownver** [comment]
Setzung des Labels "ready for review" im Namen des Autors.
Überprüfung durch @crownver und @RobinGrellner.

**Comment by crownver** [comment]
Geprüft @crownver

**Comment by RobinGrellner** [comment]
Geprüft @RobinGrellner
