### ISSUE TITLE
Testen

### ISSUE THREAD

**Issue by crownver** [sweIhm-ws2018-19/skillproject-do-2#45]
Aufgabe:

Erstellen Sie JUnit-Tests. JUnit-Tests stehen in einem Maven Projekt unter dem Verzeichnis src/test/java.Testen Sie automatisiert.

**Comment by Rybak07** [comment]
Ich habe heute Test für alle Methoden von Drink, Ingredient, Flavor und Daytime geschrieben.

**Comment by RobinGrellner** [comment]
Da die Tests für Handler etwas komplizierter sind und für diesen Sprint laut Vorgabe noch nicht benötigt, fallen diese vorerst weg.
Zudem komplette Abdeckung der ListOfDrinks Klasse, welche von @fhaala erstellt und getestet wurde. 
Tests laufen bei dem Maven build über Windows erst mit dem Command " -Dproject.build.sourceEncoding=UTF-8", da sonst das Maven encoding auf das Standard encoding von Eclipse (Cp1252) zugreift, und damit Umlaute nicht richtig verwertet werden.
