### ISSUE TITLE
Gelöscht

### ISSUE THREAD

**Issue by crownver** [sweIhm-ws2018-19/skillproject-do-2#49]
Hier bitte alle Fragen die sich euch stellen und welche ihr gern von Fr. Socher beantwortet haben wollt. 
Die Sammlung an Fragen werde ich dann immer zum nächsten Praktikum (bei dringenden Sachen per Mail) nachfragen.

**Comment by crownver** [comment]
Frage: Wie kann ich bei Markdown - in einer Tabelle - eine Aufzählung machen? Siehe Wiki Sprint 1

**Comment by fhaala** [comment]
Da ist doch eine drin? Oder stört dich, dass die Punkte nicht untereinander dargestellt werden?

**Comment by crownver** [comment]
Mich stört das Layout, finde aber leider nichts hilfreiches online. Werde am Donnerstag nachfragen ob sie einen Tipp hat.
