### ISSUE TITLE
Übungsblatt UseCaseAktivitaetSequenzDiagramme Aufgabe 3 [Reviewer: Felix Haala, Robin Grellner, Xaver Siodlazek]

### ISSUE THREAD

**Issue by crownver** [sweIhm-ws2018-19/skillproject-do-2#5]
Hier diskutieren wir die Lösung zu oben genannter Aufgabe. Die Aufgabenstellung anbei.

![grafik](https://user-images.githubusercontent.com/38068315/47493982-ea054f80-d850-11e8-9a1e-b4eca9a3c458.png)

**Comment by Rybak07** [comment]
Erster Lösungsvorschlag zur Aufgabe 3.
<img width="655" alt="aufgabe_3" src="https://user-images.githubusercontent.com/42803737/47553364-3743f880-d907-11e8-9943-b625fc3672b7.png">

**Comment by fhaala** [comment]
Ich glaube, dass die Beschriftungen schon passen. Vergleiche mal Seite 257 aus dem Buch mit dem Diagramm, da sollten die Pfeile nicht ausgemalt sein - korrekt?

**Comment by Rybak07** [comment]
Richitg. Die Pfeile sollten nicht ausgemalt sein. Ich könnte "Eingeben" noch zu "Fahrt eingeben" und "Suche" zu "Fahrt suchen", was meint Ihr? Den neuen Lösungsvorschlag lade ich hoch sobald wir das entschieden haben.

**Comment by fhaala** [comment]
Ich denke, dass wir die Fahrten nicht in die Ellipsen schreiben müssen, da das ganze System fahrten heißt. Damit ist die Zuordnung zumindest für mich eindeutig: Oben steht im Viereck Fahrten und in den Ellipsen die Fälle Eingeben, Suchen, Absagen.

**Comment by Rybak07** [comment]
Hier mein neuer Lösungsvorschlag. Wenn es passt würde ich das Issue schließen.

**Comment by Rybak07** [comment]
<img width="554" alt="aufgabe_3" src="https://user-images.githubusercontent.com/42803737/47746499-803cd980-dc86-11e8-82d7-b96d2949221f.png">

**Comment by fhaala** [comment]
Für mich hat sich da nichts verändert?

**Comment by crownver** [comment]
Die gestrichelten Linien sollten auch Pfeile darstellen (siehe Angabe)

**Comment by crownver** [comment]
Vielen dank. Damit schließe ich dann auch dieses Issue.
