### ISSUE TITLE
Diagramme 

### ISSUE THREAD

**Issue by crownver** [sweIhm-ws2018-19/skillproject-do-2#54]
Wieder sind zu allen neuen Inhalten Diagramme zu erstellen.

**Comment by crownver** [comment]
Durch die Änderungen am Projekt wird dieser Punkt größer ausfallen als gedacht. 
@Rybak07 arbeitet jedoch schon daran und steht kurz vor der Fertigstellung.

**Comment by Rybak07** [comment]
Hier das neue Fachklassendiagramm:
<img width="675" alt="klassendiagramm" src="https://user-images.githubusercontent.com/42803737/49802867-870f3f80-fd4e-11e8-835e-72401cd70fcf.png">

**Comment by fhaala** [comment]
Hier wäre ein kleines Update nötig. Durch kleine Fehler mussten die Daytime Klasse, die getRandom... Methoden sowie die drinkFitsDaytime Methode abgeändert werden.

**Comment by Rybak07** [comment]
Hier das neue Sequenzdiagramm zu Zutaten abfragen:
<img width="519" alt="sequenzdiagrammzutatenabfragen" src="https://user-images.githubusercontent.com/42803737/49865430-34dd2580-fe05-11e8-87bd-f892b19b17e9.png">

**Comment by Rybak07** [comment]
Hier das neue Klassendiagramm mit den von Felix gewünschten änderungen und den neuen HelpIntentHandlern.
<img width="1319" alt="klassendiagramm" src="https://user-images.githubusercontent.com/42803737/49885888-aaaeb480-fe38-11e8-8451-a1d9d2be1351.png">
