### ISSUE TITLE
Sprintcrash - Sprint 2

### ISSUE THREAD

**Issue by crownver** [sweIhm-ws2018-19/skillproject-do-2#57]
1. Die Funktionen "Drink eingeben" und "Drink löschen" werden nicht weiter verfolgt und damit gelöscht. 
Es ist keine Implementierung mehr vorgesehen. 
Die zugehörigen Issues wurden zurück ins Project Backlog verschoben und mit dem Label "Delete" versehen @crownver 

2. Nötige Änderungen und Neufassungen der User-Stories, Anwendungsfalldiagramme, UML-Diagramme, ..., werden von @Rybak07 vorgenommen. 

3. Die Implementierung der neuen Funktionen fällt @RobinGrellner und @fhaala zu. 

Die vorgesehen Änderungen sind:
- Drink-Liste auf 10 Stück reduzieren
- Zubereitungsschritte zu den Drinks hinzufügen
- Rezept ausgeben lassen mit den Funktionen weiter & zurück

**Comment by crownver** [comment]
1. Die Funktionen "Drink eingeben" und "Drink löschen" werden nicht weiter verfolgt und damit gelöscht. 
Es ist keine Implementierung mehr vorgesehen. 
Die zugehörigen Issues wurden zurück ins Project Backlog verschoben und mit dem Label "Delete" versehen @crownver 

2. Nötige Änderungen und Neufassungen der User-Stories, Anwendungsfalldiagramme, UML-Diagramme, ..., werden von @Rybak07 vorgenommen. 

3. Die Implementierung der neuen Funktionen fällt @RobinGrellner und @fhaala zu. 

Die vorgesehen Änderungen sind:
- Drink-Liste auf 10 Stück reduzieren
- Zubereitungsschritte zu den Drinks hinzufügen
- Rezept ausgeben lassen mit den Funktionen weiter & zurück

**Comment by crownver** [comment]
Die Funktionalität der Funktion "Drink vorschlagen" wird, anhand der Unwichtigkeit des Parameters Zeit, eingeschränkt.

**Comment by Rybak07** [comment]
User Story zur neuen Funktion "Rezept abfragen"
<img width="725" alt="user story screenshot" src="https://user-images.githubusercontent.com/42803737/49588040-fdcec600-f965-11e8-8bbb-64087db8ff37.png">
:

**Comment by Rybak07** [comment]
Die Funktion "Drink vorschlagen" wurde wie von @crownver  bereits erwähnt geändert. Hier die neue User Story dazu:
<img width="720" alt="user story2 screenshot" src="https://user-images.githubusercontent.com/42803737/49588371-d0cee300-f966-11e8-9ed0-7c1297e94593.png">

**Comment by fhaala** [comment]
Die Logik zur Rezeptabfrage und Zutatenabfrage sowie der gesamte Umbau der Java-Classen ist erfolgt. Tests wurden erstellt. Es fehlen nur noch die Intents von Robin samt Tests.

**Comment by crownver** [comment]
Da es sich nun doch nicht nur um Cocktails handelt und die Zeit bereits mit implementiert wurde von @fhaala muss die User Story wieder zurückverändert werden.
