### ISSUE TITLE
Übungsblatt UseCaseAktivitaetSequenzDiagramme Aufgabe 4 [Reviewer: Alexander Heinritzi, Felix Haala, Xaver Siodlazek]

### ISSUE THREAD

**Issue by crownver** [sweIhm-ws2018-19/skillproject-do-2#6]
Hier diskutieren wir die Lösung zu oben genannter Aufgabe. Die Aufgabenstellung anbei.

<img src = "https://user-images.githubusercontent.com/38068315/47494028-04d7c400-d851-11e8-886b-bf1499cbad84.png" width = "500" height = "600">

**Comment by crownver** [comment]
Sollen die Aktivitäten wirklich parallel ablaufen? Konnte dies nicht rauslesen. 
Wenn ja, dann super Arbeit.

**Comment by crownver** [comment]
**Bitte lade deinen Vorschlag (png und xml) auch mit der Betitelung Aufgabe_4 in folgende Ordnerstruktur 
.../UML/Uebung_2/Aufgabe_4** 
@RobinGrellner

**Comment by crownver** [comment]
Nvm, grade gesehen, dass du sie nur falsch betitelt hast, ich ändere das schnell.

**Comment by RobinGrellner** [comment]
@crownver Merci dir!
Ich hatte nochmal nachgefragt bzgl. der Parallelisiserung, da hieß es, die Hauptaufgabe sei nicht der technische Aspekt des Ablaufs, sondern dass das Konzept der Parallelisierung eingebaut wird.

**Comment by crownver** [comment]
<img src="https://raw.githubusercontent.com/sweIhm-ws2018-19/skillproject-do-2/master/UML/Uebung_2/Aufgabe_4/Aufgabe_4.PNG" alt="Aufgabe_4" width="450" height="600">

**Comment by crownver** [comment]
Da es bei obiger Grafik bzgl des Namens ein Problem gibt.

**Comment by fhaala** [comment]
Ich bin damit leider noch nicht ganz zufrieden. Es sollen Entscheidung, Synchronisation und Zusammenführung geübt werden. Der Blitz löst nur aus, falls das Licht zu schwach ist (Belichtung messen). Also muss hier noch die Entscheidung mit eingebaut werden. Außerdem würde ich dich bitten, wie in der Vorlage, einen Rahmen mit dem Titel einzubauen.

**Comment by RobinGrellner** [comment]
@fhaala So, die Änderungen die du angemerkt hast sind gemacht worden. 
Bitte nocheinmal überprüfen!

**Comment by fhaala** [comment]
Sieht für mich gut aus. Was sagt der Rest?

**Comment by crownver** [comment]
Sieht super aus.

**Comment by Rybak07** [comment]
Finde ich auch gut.
