### ISSUE TITLE
Abschlusspräsentation

### ISSUE THREAD

**Issue by crownver** [sweIhm-ws2018-19/skillproject-do-2#61]
Agenda der Präsentation:

- Skill Demo 
- Wählen Sie aus den in diesem Semester erstellten UML-Diagrammen geeignete Diagramme aus, um die Umsetzung Ihres Produkts zu erklären.
- Dokumentieren Sie Ihr Projekt unter der Verwendung von Github Pages. Nutzen Sie für die Präsentation ausschließlich Ihr Github Repository (Wiki, README, Github Pages). Zeigen Sie in Ihrer Abschlusspräsentation 
  - Systemidee und Skizze des Product Backlog
  - Fachklassenmodell (Analyseklassenmodell) (Überblick sowie Zoomen auf einzelne Klassen), aktualisieren Sie das Fachklassenmodell auf das was Sie implementiert haben eine Ihrer User Stories und ihre Umsetzung (wählen Sie hier ein "Highlight" aus)
- Zusammenfassung der gesammelten Erfahrungen Praktikum Software Engineering I (was hat sich bewährt, was werden Sie in Zukunft anders machen)

Für die Abschlusspräsentation besteht Anwesenheitspflicht.

**Comment by crownver** [comment]
Agenda der Präsentation:

    Skill Demo 
    Wählen Sie aus den in diesem Semester erstellten UML-Diagrammen geeignete Diagramme aus, um die Umsetzung Ihres Produkts zu erklären.
    Dokumentieren Sie Ihr Projekt unter der Verwendung von Github Pages. Nutzen Sie für die Präsentation ausschließlich Ihr Github Repository (Wiki, README, Github Pages). Zeigen Sie in Ihrer Abschlusspräsentation 
        Systemidee und Skizze des Product Backlog
        Fachklassenmodell (Analyseklassenmodell) (Überblick sowie Zoomen auf einzelne Klassen), aktualisieren Sie das Fachklassenmodell auf das was Sie implementiert haben
        eine Ihrer User Stories und ihre Umsetzung (wählen Sie hier ein "Highlight" aus)
        Zusammenfassung der gesammelten Erfahrungen Praktikum Software Engineering I (was hat sich bewährt, was werden Sie in Zukunft anders machen)

Für die Abschlusspräsentation besteht Anwesenheitspflicht.

**Comment by Rybak07** [comment]
Hier das aktuelle Klassendiagramm:
<img width="1031" alt="klassendiagramm" src="https://user-images.githubusercontent.com/42803737/50738410-d0c73a80-11d3-11e9-84aa-3d5bdc322de1.png">

**Comment by Rybak07** [comment]
Hier das aktuelle Sequenzdiagramm zu Drink vorschlagen:

<img width="871" alt="drinkvorschlagen" src="https://user-images.githubusercontent.com/42803737/50738418-e63c6480-11d3-11e9-846a-ba7d88393830.png">

**Comment by crownver** [comment]
![anwendungsfall](https://user-images.githubusercontent.com/38068315/50782780-3df8cf80-12a9-11e9-8c4b-f05219dffb74.png)


final
