### ISSUE TITLE
Übungsblatt UseCaseAktivitaetSequenzDiagramme Aufgabe 6 [Reviewer: Alexander Heinritzi, Robin Grellner, Felix Haala]

### ISSUE THREAD

**Issue by crownver** [sweIhm-ws2018-19/skillproject-do-2#8]
Hier diskutieren wir die Lösung der oben genannten Aufgabe. Die Aufgabenstellung anbei.

![grafik](https://user-images.githubusercontent.com/38068315/47494136-45cfd880-d851-11e8-9ba9-efd43db51c8b.png)

**Comment by RobinGrellner** [comment]
Bezüglich des Erfassens/Aktualisierens der Kundendaten denke ich sollte das so passen. Bei der Parallelität bzgl. 2/2a weiss ich leider auch nciht weiter, vermute aber dass diese nicht parallel ablaufen (können). 
Muss der Kunde als Auslöser im Diagramm vorkommen?

**Comment by Rybak07** [comment]
Ich denke, dass der Ablauf so passt. Nur sollten noch die Bedingungen bei der Entscheidung eingefügt werden. Bei "Verfügbarkeit des Artikels" sollte am ende noch "prüfen" eingefügt werden. Außerdem sollte es "Kundensachbearbeiter" statt "Kundenberater" heißen.

**Comment by crownver** [comment]
Hast natürlich recht, werde ich sofort ändern.

**Comment by crownver** [comment]
@RobinGrellner würdest du deinen Lösungsvorschlag auch noch uploaden bitte?

**Comment by crownver** [comment]
Das "prüfen" bei "Verfügbarkeit jedes Artikels prüfen" wurde von draw.io beim extrahieren herausgeschnitten, komisch..
Naja, jetzt sollte alles passen oder?

<img src="https://raw.githubusercontent.com/sweIhm-ws2018-19/skillproject-do-2/master/UML/Uebung_2/Aufgabe_6/Aufgabe_6.png" alt="Aufgabe_6" width="500" height="300">

**Comment by crownver** [comment]
Wie ich sehe passt es nicht, echt komisch..

**Comment by crownver** [comment]
So, habe jetzt für jedes einzelne Wort eine eigene Textbox erstellen müssen aber jetzt sollte es passen. Der oben angezeigt Vorschlag ist schon die aktuellste Version.

**Comment by RobinGrellner** [comment]
So, ich habe nun eine neue Version der Lösung erstellt. Die Veränderungen sind in der Commit-Message zu sehen und die Datei ist unter dem Namen Aufgabe_6_vRobin auf 
[](https://github.com/sweIhm-ws2018-19/skillproject-do-2/tree/master/UML/Uebung_2/Aufgabe_6)
auffindbar.
<img src="https://github.com/sweIhm-ws2018-19/skillproject-do-2/tree/master/UML/Uebung_2/Aufgabe_6/Aufgabe_6_vRobin.png" alt="Aufgabe_6" width="" height="">

**Comment by fhaala** [comment]
Ich habe jetzt nur die allerletzte Version unten angeschaut. Ich würde bei der Zusammenführung die beiden Pfeile links und rechts an das Quadrat bauen - nirgendwo zeigen mehrere Pfeile auf eine Ecke.

Bei der Erweiterung mit 2a bin ich unsicher - nach letzter Stunde müsste das ja irgendwie extra laufen und im Fluss nicht einfach danach kommen, sonst hätte man es ja auch da hingeschrieben?

Die Auftragsbestätigung fehlt komplett.

Ich weiß nicht, warum da so viele extra Punkte "erfunden" wurden. Ich würde sagen, wir halten es einfach und uns vor allem genau an die Vorgabe... da gibtes die ganzen Abzweigungen bei Rechnung, Paketliste, Adresseaufkleber, etc. nicht.

**Comment by crownver** [comment]
Da wir nun zwei Versionen haben stehen wir im Konflikt. Die einfach gehaltene Version meinerseits und die Version von Robin mit Erweiterungen. 
Felix sprach sich gegen eine Abgabe von 2 Versionen aus und somit müssten wir noch klären welche Version wir abgeben sollen.

**Comment by Rybak07** [comment]
Ich schließe mich der Meinung von Felix an. Wir sollten uns genau an dei Vorgabe halten. Deshalb würde ich sagen wier geben Xavers Lösung ab.

**Comment by crownver** [comment]
Alles klar. Mit einer Mehrheit von 3 Stimmen und im vollem Bewusstsein das wir die Verantwortung für diese Entscheidung tragen, werde ich nur meine Lösung im Wiki aufnehmen und die von Robin umbennen. 
Damit schließe ich nun auch das letzte Issue.
